package com.insta.entities;

// Generated Aug 2, 2015 3:40:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstaImageData generated by hbm2java
 */
@Entity
@Table(name = "insta_image_data", schema = "public")
public class InstaImageData implements java.io.Serializable {

	private long imageDataId;
	private InstaImage instaImage;
	private byte[] imageBytes;
	private Date imageDataCreatedDate;

	public InstaImageData() {
	}

	public InstaImageData(long imageDataId, InstaImage instaImage,
			byte[] imageBytes, Date imageDataCreatedDate) {
		this.imageDataId = imageDataId;
		this.instaImage = instaImage;
		this.imageBytes = imageBytes;
		this.imageDataCreatedDate = imageDataCreatedDate;
	}

	@Id
	@Column(name = "image_data_id", unique = true, nullable = false)
	public long getImageDataId() {
		return this.imageDataId;
	}

	public void setImageDataId(long imageDataId) {
		this.imageDataId = imageDataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public InstaImage getInstaImage() {
		return this.instaImage;
	}

	public void setInstaImage(InstaImage instaImage) {
		this.instaImage = instaImage;
	}

	@Column(name = "image_bytes", nullable = false)
	public byte[] getImageBytes() {
		return this.imageBytes;
	}

	public void setImageBytes(byte[] imageBytes) {
		this.imageBytes = imageBytes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "image_data_created_date", nullable = false, length = 29)
	public Date getImageDataCreatedDate() {
		return this.imageDataCreatedDate;
	}

	public void setImageDataCreatedDate(Date imageDataCreatedDate) {
		this.imageDataCreatedDate = imageDataCreatedDate;
	}

}
