package com.insta.entities;

// Generated Aug 2, 2015 3:40:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstaVideoComments generated by hbm2java
 */
@Entity
@Table(name = "insta_video_comments", schema = "public")
public class InstaVideoComments implements java.io.Serializable {

	private long videoComentsId;
	private InstaUser instaUser;
	private InstaVideo instaVideo;
	private String videoComments;
	private Date videoCommentsCreatedDate;

	public InstaVideoComments() {
	}

	public InstaVideoComments(long videoComentsId, InstaUser instaUser,
			InstaVideo instaVideo, String videoComments,
			Date videoCommentsCreatedDate) {
		this.videoComentsId = videoComentsId;
		this.instaUser = instaUser;
		this.instaVideo = instaVideo;
		this.videoComments = videoComments;
		this.videoCommentsCreatedDate = videoCommentsCreatedDate;
	}

	@Id
	@Column(name = "video_coments_id", unique = true, nullable = false)
	public long getVideoComentsId() {
		return this.videoComentsId;
	}

	public void setVideoComentsId(long videoComentsId) {
		this.videoComentsId = videoComentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public InstaUser getInstaUser() {
		return this.instaUser;
	}

	public void setInstaUser(InstaUser instaUser) {
		this.instaUser = instaUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "video_id", nullable = false)
	public InstaVideo getInstaVideo() {
		return this.instaVideo;
	}

	public void setInstaVideo(InstaVideo instaVideo) {
		this.instaVideo = instaVideo;
	}

	@Column(name = "video_comments", nullable = false, length = 4000)
	public String getVideoComments() {
		return this.videoComments;
	}

	public void setVideoComments(String videoComments) {
		this.videoComments = videoComments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "video_comments_created_date", nullable = false, length = 29)
	public Date getVideoCommentsCreatedDate() {
		return this.videoCommentsCreatedDate;
	}

	public void setVideoCommentsCreatedDate(Date videoCommentsCreatedDate) {
		this.videoCommentsCreatedDate = videoCommentsCreatedDate;
	}

}
