package com.insta.entities;

// Generated Aug 2, 2015 3:40:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstaImageLikes generated by hbm2java
 */
@Entity
@Table(name = "insta_image_likes", schema = "public")
public class InstaImageLikes implements java.io.Serializable {

	private long imageLikesId;
	private InstaImage instaImage;
	private int likesNumber;
	private long userId;
	private Date ratingCreatedDate;

	public InstaImageLikes() {
	}

	public InstaImageLikes(long imageLikesId, InstaImage instaImage,
			int likesNumber, long userId, Date ratingCreatedDate) {
		this.imageLikesId = imageLikesId;
		this.instaImage = instaImage;
		this.likesNumber = likesNumber;
		this.userId = userId;
		this.ratingCreatedDate = ratingCreatedDate;
	}

	@Id
	@Column(name = "image_likes_id", unique = true, nullable = false)
	public long getImageLikesId() {
		return this.imageLikesId;
	}

	public void setImageLikesId(long imageLikesId) {
		this.imageLikesId = imageLikesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public InstaImage getInstaImage() {
		return this.instaImage;
	}

	public void setInstaImage(InstaImage instaImage) {
		this.instaImage = instaImage;
	}

	@Column(name = "likes_number", nullable = false)
	public int getLikesNumber() {
		return this.likesNumber;
	}

	public void setLikesNumber(int likesNumber) {
		this.likesNumber = likesNumber;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rating_created_date", nullable = false, length = 29)
	public Date getRatingCreatedDate() {
		return this.ratingCreatedDate;
	}

	public void setRatingCreatedDate(Date ratingCreatedDate) {
		this.ratingCreatedDate = ratingCreatedDate;
	}

}
