package com.insta.entities;

// Generated Aug 2, 2015 3:40:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstaImageComments generated by hbm2java
 */
@Entity
@Table(name = "insta_image_comments", schema = "public")
public class InstaImageComments implements java.io.Serializable {

	private long imageComentsId;
	private InstaImage instaImage;
	private InstaUser instaUser;
	private String imageComments;
	private Date imageCommentsCreatedDate;

	public InstaImageComments() {
	}

	public InstaImageComments(long imageComentsId, InstaImage instaImage,
			InstaUser instaUser, String imageComments,
			Date imageCommentsCreatedDate) {
		this.imageComentsId = imageComentsId;
		this.instaImage = instaImage;
		this.instaUser = instaUser;
		this.imageComments = imageComments;
		this.imageCommentsCreatedDate = imageCommentsCreatedDate;
	}

	@Id
	@Column(name = "image_coments_id", unique = true, nullable = false)
	public long getImageComentsId() {
		return this.imageComentsId;
	}

	public void setImageComentsId(long imageComentsId) {
		this.imageComentsId = imageComentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public InstaImage getInstaImage() {
		return this.instaImage;
	}

	public void setInstaImage(InstaImage instaImage) {
		this.instaImage = instaImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public InstaUser getInstaUser() {
		return this.instaUser;
	}

	public void setInstaUser(InstaUser instaUser) {
		this.instaUser = instaUser;
	}

	@Column(name = "image_comments", nullable = false, length = 4000)
	public String getImageComments() {
		return this.imageComments;
	}

	public void setImageComments(String imageComments) {
		this.imageComments = imageComments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "image_comments_created_date", nullable = false, length = 29)
	public Date getImageCommentsCreatedDate() {
		return this.imageCommentsCreatedDate;
	}

	public void setImageCommentsCreatedDate(Date imageCommentsCreatedDate) {
		this.imageCommentsCreatedDate = imageCommentsCreatedDate;
	}

}
