package com.insta.entities;

// Generated Aug 2, 2015 1:38:10 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * InstaUserRole generated by hbm2java
 */
@Entity
@Table(name = "insta_user_role", schema = "public")
public class InstaUserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4280656690295521501L;
	private long userRoleId;
	private InstaUser instaUser;
	private String userRoleUsername;
	private String userRoleRole;
	private Date userRoleCreatedDate;
	private Date userRoleUpdatedDate;

	public InstaUserRole() {
	}

	public InstaUserRole(long userRoleId, InstaUser instaUser,
			String userRoleUsername, String userRoleRole,
			Date userRoleCreatedDate, Date userRoleUpdatedDate) {
		this.userRoleId = userRoleId;
		this.instaUser = instaUser;
		this.userRoleUsername = userRoleUsername;
		this.userRoleRole = userRoleRole;
		this.userRoleCreatedDate = userRoleCreatedDate;
		this.userRoleUpdatedDate = userRoleUpdatedDate;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public InstaUser getInstaUser() {
		return this.instaUser;
	}

	public void setInstaUser(InstaUser instaUser) {
		this.instaUser = instaUser;
	}

	@Column(name = "user_role_username", nullable = false, length = 50)
	public String getUserRoleUsername() {
		return this.userRoleUsername;
	}

	public void setUserRoleUsername(String userRoleUsername) {
		this.userRoleUsername = userRoleUsername;
	}

	@Column(name = "user_role_role", nullable = false, length = 50)
	public String getUserRoleRole() {
		return this.userRoleRole;
	}

	public void setUserRoleRole(String userRoleRole) {
		this.userRoleRole = userRoleRole;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_role_created_date", nullable = false, length = 29)
	public Date getUserRoleCreatedDate() {
		return this.userRoleCreatedDate;
	}

	public void setUserRoleCreatedDate(Date userRoleCreatedDate) {
		this.userRoleCreatedDate = userRoleCreatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_role_updated_date", nullable = false, length = 29)
	public Date getUserRoleUpdatedDate() {
		return this.userRoleUpdatedDate;
	}

	public void setUserRoleUpdatedDate(Date userRoleUpdatedDate) {
		this.userRoleUpdatedDate = userRoleUpdatedDate;
	}

}
