package com.insta.entities;

// Generated Aug 2, 2015 3:40:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstaVideo generated by hbm2java
 */
@Entity
@Table(name = "insta_video", schema = "public")
public class InstaVideo implements java.io.Serializable {

	private long videoId;
	private InstaUser instaUser;
	private String videoName;
	private String videoDescription;
	private boolean videoIsPrivate;
	private Date videoCreatedDate;
	private Date videoUpdatedDate;
	private String videoCreatedBy;
	private String videoUpdatedBy;
	private Set<InstaVideoComments> instaVideoCommentses = new HashSet<InstaVideoComments>(
			0);

	public InstaVideo() {
	}

	public InstaVideo(long videoId, InstaUser instaUser, String videoName,
			boolean videoIsPrivate, Date videoCreatedDate, Date videoUpdatedDate) {
		this.videoId = videoId;
		this.instaUser = instaUser;
		this.videoName = videoName;
		this.videoIsPrivate = videoIsPrivate;
		this.videoCreatedDate = videoCreatedDate;
		this.videoUpdatedDate = videoUpdatedDate;
	}

	public InstaVideo(long videoId, InstaUser instaUser, String videoName,
			String videoDescription, boolean videoIsPrivate,
			Date videoCreatedDate, Date videoUpdatedDate,
			String videoCreatedBy, String videoUpdatedBy,
			Set<InstaVideoComments> instaVideoCommentses) {
		this.videoId = videoId;
		this.instaUser = instaUser;
		this.videoName = videoName;
		this.videoDescription = videoDescription;
		this.videoIsPrivate = videoIsPrivate;
		this.videoCreatedDate = videoCreatedDate;
		this.videoUpdatedDate = videoUpdatedDate;
		this.videoCreatedBy = videoCreatedBy;
		this.videoUpdatedBy = videoUpdatedBy;
		this.instaVideoCommentses = instaVideoCommentses;
	}

	@Id
	@Column(name = "video_id", unique = true, nullable = false)
	public long getVideoId() {
		return this.videoId;
	}

	public void setVideoId(long videoId) {
		this.videoId = videoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "video_user_id", nullable = false)
	public InstaUser getInstaUser() {
		return this.instaUser;
	}

	public void setInstaUser(InstaUser instaUser) {
		this.instaUser = instaUser;
	}

	@Column(name = "video_name", nullable = false, length = 100)
	public String getVideoName() {
		return this.videoName;
	}

	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	@Column(name = "video_description", length = 4000)
	public String getVideoDescription() {
		return this.videoDescription;
	}

	public void setVideoDescription(String videoDescription) {
		this.videoDescription = videoDescription;
	}

	@Column(name = "video_is_private", nullable = false)
	public boolean isVideoIsPrivate() {
		return this.videoIsPrivate;
	}

	public void setVideoIsPrivate(boolean videoIsPrivate) {
		this.videoIsPrivate = videoIsPrivate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "video_created_date", nullable = false, length = 29)
	public Date getVideoCreatedDate() {
		return this.videoCreatedDate;
	}

	public void setVideoCreatedDate(Date videoCreatedDate) {
		this.videoCreatedDate = videoCreatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "video_updated_date", nullable = false, length = 29)
	public Date getVideoUpdatedDate() {
		return this.videoUpdatedDate;
	}

	public void setVideoUpdatedDate(Date videoUpdatedDate) {
		this.videoUpdatedDate = videoUpdatedDate;
	}

	@Column(name = "video_created_by", length = 100)
	public String getVideoCreatedBy() {
		return this.videoCreatedBy;
	}

	public void setVideoCreatedBy(String videoCreatedBy) {
		this.videoCreatedBy = videoCreatedBy;
	}

	@Column(name = "video_updated_by", length = 100)
	public String getVideoUpdatedBy() {
		return this.videoUpdatedBy;
	}

	public void setVideoUpdatedBy(String videoUpdatedBy) {
		this.videoUpdatedBy = videoUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instaVideo")
	public Set<InstaVideoComments> getInstaVideoCommentses() {
		return this.instaVideoCommentses;
	}

	public void setInstaVideoCommentses(
			Set<InstaVideoComments> instaVideoCommentses) {
		this.instaVideoCommentses = instaVideoCommentses;
	}

}
